// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("http://localhost:3000/tasks")
    await driver.manage().window().setRect({ width: 1536, height: 824 })
    await driver.findElement(By.linkText("Add")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).click()
    {
      const element = await driver.findElement(By.id("title"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("title")).sendKeys("qw")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("er")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Tasks")).click()
    {
      const element = await driver.findElement(By.linkText("Tasks"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".form-control")).click()
    await driver.findElement(By.css(".form-control")).sendKeys("qw")
    await driver.findElement(By.css(".btn-outline-secondary")).click()
  })
})
